### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by GiorgosK** [pixeline/Yurl#1]
Very usefull extension perhaps something like this should be part of chrome bookmarks system

a few suggestions 

1. add an edit button next to delete button
2. More neutral colors / or configurable colors would be really appreciated
3. allow for the 2nd line of info on hover to be configurable / people might find it distracting :smiley:
and might prefer for it not to be shown

**Comment by pixeline** [comment]
It makes sense, i'll  see what i can do!

**Comment by pixeline** [comment]
I've transfered your comments as individual items in the Roadmap (see project board). Wil close this for now. Thanks a lot again @GiorgosK !
